import os
import re

import psycopg
from psycopg.rows import dict_row


# Read the Supabase connection string from Render.
# strip() removes hidden spaces or line breaks.
DATABASE_URL = (
    os.getenv("DATABASE_URL") or ""
).strip()

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL environment variable is required."
    )


def convert_sql(sql):
    """
    Convert the SQLite-style SQL still used in app.py
    into PostgreSQL-compatible SQL.
    """

    converted = sql.strip()

    if converted.upper() == "BEGIN IMMEDIATE":
        return "BEGIN"

    converted = converted.replace(
        "datetime('now', '+15 minutes')",
        "CURRENT_TIMESTAMP + INTERVAL '15 minutes'",
    )

    insert_or_ignore = bool(
        re.match(
            r"^\s*INSERT\s+OR\s+IGNORE\s+INTO",
            converted,
            flags=re.IGNORECASE,
        )
    )

    if insert_or_ignore:
        converted = re.sub(
            r"^\s*INSERT\s+OR\s+IGNORE\s+INTO",
            "INSERT INTO",
            converted,
            count=1,
            flags=re.IGNORECASE,
        )

        converted = converted.rstrip().rstrip(";")
        converted += " ON CONFLICT DO NOTHING"

    # SQLite placeholders use ? while PostgreSQL uses %s.
    converted = converted.replace("?", "%s")

    return converted


class CursorProxy:
    def __init__(
        self,
        cursor,
        lastrowid=None,
    ):
        self._cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self):
        return self._cursor.rowcount

    def fetchone(self):
        return self._cursor.fetchone()

    def fetchall(self):
        return self._cursor.fetchall()

    def close(self):
        self._cursor.close()


class ConnectionProxy:
    def __init__(self, connection):
        self._connection = connection

    def execute(
        self,
        sql,
        parameters=None,
    ):
        converted_sql = convert_sql(sql)

        if parameters is None:
            parameters = ()

        cursor = self._connection.cursor()

        is_insert = (
            converted_sql
            .lstrip()
            .upper()
            .startswith("INSERT INTO")
        )

        has_returning = bool(
            re.search(
                r"\bRETURNING\b",
                converted_sql,
                flags=re.IGNORECASE,
            )
        )

        lastrowid = None

        if is_insert and not has_returning:
            converted_sql = (
                converted_sql
                .rstrip()
                .rstrip(";")
                + " RETURNING id"
            )

            cursor.execute(
                converted_sql,
                parameters,
            )

            inserted_row = cursor.fetchone()

            if inserted_row:
                lastrowid = inserted_row["id"]

        else:
            cursor.execute(
                converted_sql,
                parameters,
            )

        return CursorProxy(
            cursor,
            lastrowid=lastrowid,
        )

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


def get_connection():
    """
    Connect to Supabase PostgreSQL.
    SSL is required separately so it cannot be affected
    by hidden spaces in the Render connection string.
    """

    connection = psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row,
        connect_timeout=20,
        sslmode="require",
    )

    return ConnectionProxy(connection)


def init_db():
    """
    Create the required tables and indexes.
    Existing Supabase data is preserved.
    """

    conn = get_connection()

    try:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT
                    AS IDENTITY PRIMARY KEY,
                username VARCHAR(50)
                    UNIQUE NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMP NOT NULL
                    DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                id BIGINT GENERATED BY DEFAULT
                    AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                price DOUBLE PRECISION NOT NULL,
                stock INTEGER NOT NULL DEFAULT 0,
                user_id BIGINT,
                CONSTRAINT products_user_fk
                    FOREIGN KEY (user_id)
                    REFERENCES users (id)
                    ON DELETE CASCADE
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS sales (
                id BIGINT GENERATED BY DEFAULT
                    AS IDENTITY PRIMARY KEY,
                product_id BIGINT NOT NULL,
                quantity INTEGER NOT NULL,
                total_amount DOUBLE PRECISION NOT NULL,
                sale_time TIMESTAMP NOT NULL
                    DEFAULT CURRENT_TIMESTAMP,
                matched INTEGER NOT NULL DEFAULT 0,
                user_id BIGINT,
                CONSTRAINT sales_product_fk
                    FOREIGN KEY (product_id)
                    REFERENCES products (id),
                CONSTRAINT sales_user_fk
                    FOREIGN KEY (user_id)
                    REFERENCES users (id)
                    ON DELETE CASCADE
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS mpesa_transactions (
                id BIGINT GENERATED BY DEFAULT
                    AS IDENTITY PRIMARY KEY,
                mpesa_code VARCHAR(30)
                    UNIQUE NOT NULL,
                sender_name VARCHAR(100),
                amount DOUBLE PRECISION NOT NULL,
                transaction_time TIMESTAMP NOT NULL
                    DEFAULT CURRENT_TIMESTAMP,
                matched INTEGER NOT NULL DEFAULT 0,
                user_id BIGINT,
                CONSTRAINT mpesa_user_fk
                    FOREIGN KEY (user_id)
                    REFERENCES users (id)
                    ON DELETE CASCADE
            )
            """
        )

        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS pending_stk_requests (
                id BIGINT GENERATED BY DEFAULT
                    AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL,
                checkout_request_id TEXT
                    UNIQUE NOT NULL,
                phone_number VARCHAR(20) NOT NULL,
                amount DOUBLE PRECISION NOT NULL,
                status VARCHAR(30) NOT NULL
                    DEFAULT 'pending',
                mpesa_receipt VARCHAR(50),
                product_id BIGINT,
                quantity INTEGER,
                stock_reserved INTEGER NOT NULL
                    DEFAULT 0,
                created_at TIMESTAMP NOT NULL
                    DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP NOT NULL
                    DEFAULT CURRENT_TIMESTAMP,
                expires_at TIMESTAMP,
                CONSTRAINT pending_user_fk
                    FOREIGN KEY (user_id)
                    REFERENCES users (id)
                    ON DELETE CASCADE,
                CONSTRAINT pending_product_fk
                    FOREIGN KEY (product_id)
                    REFERENCES products (id)
            )
            """
        )

        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS
                idx_products_user_name
            ON products (
                user_id,
                name
            )
            """
        )

        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS
                idx_sales_user_time
            ON sales (
                user_id,
                sale_time
            )
            """
        )

        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS
                idx_mpesa_user_time
            ON mpesa_transactions (
                user_id,
                transaction_time
            )
            """
        )

        conn.execute(
            """
            CREATE INDEX IF NOT EXISTS
                idx_pending_stk_user_status
            ON pending_stk_requests (
                user_id,
                status
            )
            """
        )

        conn.commit()

        print(
            "Supabase PostgreSQL database "
            "initialized successfully."
        )

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


def migrate_existing_data_to_user(username):
    """
    Assign records without a user to an existing account.
    """

    conn = get_connection()

    try:
        user = conn.execute(
            """
            SELECT id
            FROM users
            WHERE username = ?
            """,
            (username,),
        ).fetchone()

        if not user:
            print(
                f"No user named '{username}' found."
            )
            return

        user_id = user["id"]

        conn.execute(
            """
            UPDATE products
            SET user_id = ?
            WHERE user_id IS NULL
            """,
            (user_id,),
        )

        conn.execute(
            """
            UPDATE sales
            SET user_id = ?
            WHERE user_id IS NULL
            """,
            (user_id,),
        )

        conn.execute(
            """
            UPDATE mpesa_transactions
            SET user_id = ?
            WHERE user_id IS NULL
            """,
            (user_id,),
        )

        conn.commit()

        print(
            f"Existing records assigned to "
            f"'{username}'."
        )

    except Exception:
        conn.rollback()
        raise

    finally:
        conn.close()


if __name__ == "__main__":
    init_db()